Logistic Regression MVP
arcium-hq/examples pull request #2
Opened 2024-12-21 06:08 UTC by arihantbansal

Possible improvements

- [ ] Array inputs for `coeff`, and `input`
- [ ] Import existing model weights using some lib and showcase in test (?)

2024-12-21 15:58 UTC, cryptopapi997 requested changes

2024-12-21 15:58 UTC, cryptopapi997 commented on predictor/programs/predictor/src/lib.rs
> +const COMP_DEF_OFFSET_ADD_TOGETHER: u32 = comp_def_offset("add_together");
Wrong const name & more importantly wrong name for conf instruction

2024-12-21 15:58 UTC, cryptopapi997 commented on predictor/tests/predictor.ts
> +  const program = anchor.workspace.PricePredict as Program<Predictor>;
```suggestion
  const program = anchor.workspace.Predictor as Program<Predictor>;
```

2024-12-21 15:58 UTC, cryptopapi997 commented on predictor/tests/predictor.ts
> +    program: Program<PricePredict>,
```suggestion
    program: Program<Predictor>,
```

2025-01-03 11:07 UTC, mvuille commented on predictor/confidential-ixs/src/lib.rs
> +pub fn predict(
sorry to be picky, but when it comes to terminology I would try to stick as closely as possible to the well-known libraries (probably scikit-learn here), and therefore call this function [predict_proba](https://scikit-learn.org/1.5/modules/generated/sklearn.linear_model.LogisticRegression.html#sklearn.linear_model.LogisticRegression.predict_proba), to avoid confusion with the function [predict](https://scikit-learn.org/1.5/modules/generated/sklearn.linear_model.LogisticRegression.html#sklearn.linear_model.LogisticRegression.predict)

2025-01-03 11:07 UTC, mvuille commented on predictor/confidential-ixs/src/lib.rs
> +    coeff_1: mf64,
in the same vein, we could favor `coef` instead of `coeff` here (though this is really a negligible detail)

2025-01-03 11:07 UTC, mvuille commented on predictor/tests/predictor.ts
> +    const coeff_1 = 1.1 as MFloat;
would be nice to provide some negative values too, just to test the functioning of those ;)

2025-01-03 11:27 UTC, mvuille commented on predictor/confidential-ixs/src/lib.rs
> +    input: mf64,
added the assertion [here](https://github.com/arcium-hq/arcium-tooling/pull/271)

2025-01-05 11:24 UTC, cryptopapi997 reviewed
Please also update the README as req'd in my prev review

2025-01-05 11:24 UTC, cryptopapi997 commented on predictor/Anchor.toml
> +filename = "artifacts/executing_pool_acc.json"
```suggestion
```

2026-07-03 16:20 UTC, closed without merging